# Generated by Django 4.0.1 on 2022-01-19 09:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('surname', models.CharField(max_length=50, verbose_name='фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='отчество')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='номер телефона')),
                ('image', models.ImageField(upload_to='', verbose_name='картинка')),
                ('date_of_birth', models.DateField(max_length=8, verbose_name='дата рождения')),
                ('status', models.CharField(choices=[('NA', 'не активирован'), ('AV', 'активирован'), ('DL', 'удалён')], default='NA', max_length=2)),
            ],
        ),
    ]
